GET http://localhost:4004/api/User
###
POST http://localhost:4004/api/Stock
Content-Type: application/json

{"name": "chicken", "category": "MeatAndPoultry"}

###
PUT http://localhost:4004/api/Stock('58f426c5-437e-4f02-8de2-b1ec7dac35eb')
Content-Type: application/json

{"name": "fish", "category":"Seafood"}

###
POST http://localhost:4004/api/BeneficiaryStock
Content-Type: application/json

{"beneficiary":"bene001", "stock":"58f426c5-437e-4f02-8de2-b1ec7dac35eb", "stockCount": 1}

###
GET http://localhost:4004/api/Schedule

###
GET http://localhost:4004/api/Charity

###
POST http://localhost:4004/api/Charity
Content-Type: application/json

{"name": "test", "address": "test address", "schedules": 4d05ff5a-e706-4c40-b265-594c5482cb8b}